//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppVersion
    {
        public string AppName { get; set; }
        public double AppVersion { get; set; }
        public double DatabaseVersion { get; set; }
        public string AppDescription { get; set; }
    }
}
