//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBook()
        {
            this.tblDiscount = new HashSet<tblDiscount>();
            this.tblInOut = new HashSet<tblInOut>();
            this.tblOrderDetail = new HashSet<tblOrderDetail>();
        }
    
        public int BookID { get; set; }
        public string Name { get; set; }
        public string LatinName { get; set; }
        public double Price { get; set; }
        public string Publisher { get; set; }
        public string Writer { get; set; }
        public string Translator { get; set; }
        public string ISBN { get; set; }
        public short PrintTurns { get; set; }
        public string PieceOfBook { get; set; }
        public string Summary { get; set; }
        public short PageNumber { get; set; }
        public string BookPicture { get; set; }
        public bool IsShowing { get; set; }
        public int CategoryID { get; set; }
        public string BookLanguage { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblComment tblComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDiscount> tblDiscount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInOut> tblInOut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetail { get; set; }
    }
}
