//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComment
    {
        public int CommentID { get; set; }
        public string CommentDescription { get; set; }
        public int CommentLike { get; set; }
        public int CommentDisLike { get; set; }
        public System.DateTime CommentDate { get; set; }
        public int BookID { get; set; }
        public int PersonID { get; set; }
    
        public virtual tblBook tblBook { get; set; }
        public virtual tblComment tblComment1 { get; set; }
        public virtual tblComment tblComment2 { get; set; }
        public virtual tblPerson tblPerson { get; set; }
    }
}
