//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiscount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDiscount()
        {
            this.tblOrder = new HashSet<tblOrder>();
            this.tblOrderDetail = new HashSet<tblOrderDetail>();
        }
    
        public int DiscountID { get; set; }
        public int DiscountPersent { get; set; }
        public string Discount { get; set; }
        public System.DateTime DiscountStartDate { get; set; }
        public System.DateTime DiscountEndDate { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> BookID { get; set; }
    
        public virtual tblBook tblBook { get; set; }
        public virtual tblPerson tblPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetail { get; set; }
    }
}
