//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDetail
    {
        public int OrderDetailID { get; set; }
        public double OrderDetailPrice { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public int BookID { get; set; }
        public int OrderID { get; set; }
    
        public virtual tblBook tblBook { get; set; }
        public virtual tblDiscount tblDiscount { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
